title: "FIVE POINT"
description: "Comércio e Prestação de Serviços, LDA."

url: "https://carlinhosshine-collab.github.io"
baseurl: "/five-point-site"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

logo: "/five-point-site/assets/img/logo.png"

color_scheme: light

search_enabled: true
heading_anchors: true

back_to_top: true
back_to_top_text: "Voltar ao topo"

aux_links:
  "Serviços":
    - "https://carlinhosshine-collab.github.io/five-point-site/servicos/"
  "Contacto":
    - "https://carlinhosshine-collab.github.io/five-point-site/contacto/"

footer_content: "© 2026 FIVE POINT – Comércio e Prestação de Serviços, LDA."
